### ISSUE TITLE
Question about API.

### ISSUE THREAD

**Issue by Arugin** [clibequilibrium/optick-CSharp#1]
https://github.com/clibequilibrium/optick-CSharp/blob/75fc60376f4e7ee27f903528bb039ae00c105e46/src/cs/production/optick/Program.cs#L16C1-L16C1

Shouldn't this function call be paired with OptickAPIPopEvent at the end of the function?
Otherwise I don't see "delay" event in the Optick gui (only frames are shown there).
But if I pair them, then the program crashes with memory access violation.
Am I missing something?

**Comment by clibequilibrium** [comment]
> https://github.com/clibequilibrium/optick-CSharp/blob/75fc60376f4e7ee27f903528bb039ae00c105e46/src/cs/production/optick/Program.cs#L16C1-L16C1
> 
> Shouldn't this function call be paired with OptickAPIPopEvent at the end of the function? Otherwise I don't see "delay" event in the Optick gui (only frames are shown there). But if I pair them, then the program crashes with memory access violation. Am I missing something?

You are correct. Fixed in https://github.com/clibequilibrium/optick-CSharp/commit/a076ded3d5eb734a8a9cae39cd58340cd02d6f74


![image](https://github.com/clibequilibrium/optick-CSharp/assets/105135724/3a964ba1-ef2d-4d0a-9772-78ffcb49ba16)
